
server:
  port: 8001
  servlet:
    context-path: /diseasereport

spring:
  #  profiles:
  #    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/disease_report?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone = GMT%2B8&autoReconnect=true
    username: root
    password: ls0314..
    driver-class-name: com.mysql.jdbc.Driver

